# Generated by Django 4.0.4 on 2022-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_docter_password2_patient_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docter',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='docter',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password2',
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
