# Generated by Django 4.0.4 on 2022-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_docter_salary_alter_docter_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docter',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
