# Generated by Django 4.0.4 on 2022-05-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_docter_phone_alter_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medicine',
        ),
    ]
